<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqpgpox\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqpgpox/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQqpgpox.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQqpgpox\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQqpgpox\appProdProjectContainer(array(
    'container.build_hash' => 'Qqpgpox',
    'container.build_id' => '272f9d8a',
    'container.build_time' => 1516290158,
));
