<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBnwqddu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBnwqddu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBnwqddu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBnwqddu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBnwqddu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bnwqddu',
    'container.build_id' => 'c88c8938',
    'container.build_time' => 1516453345,
));
